name: Transfer to dev env and run

on: [push]

jobs:
  build:
    name: Transfer to dev env and run
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_SSH_USERNAME }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: "/root/votong/deploy/pull.sh"
